server:
  http:
    addr: 0.0.0.0:18000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  computer_power_api: "https://computeshare.hamster.newtouch.com"
