server:
  http:
    addr: 0.0.0.0:18000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 10s
  p2p:
    gateway_ip: 61.172.179.73
    gateway_port: 7000
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  ipfs:
    url: 127.0.0.1:5001
  computer_power_api: "https://api.computeshare.newtouch.com"
#  computer_power_api: "http://127.0.0.1:8000"
  workdir: /home/mohaijiang/vm
